ALTER TABLE invoices             ADD COLUMN IF NOT EXISTS iva_pct NUMERIC DEFAULT 21;
ALTER TABLE pro_purchase_quotes  ADD COLUMN IF NOT EXISTS iva_pct NUMERIC DEFAULT 21;
ALTER TABLE pro_projects         ADD COLUMN IF NOT EXISTS iva_pct NUMERIC DEFAULT 21;
